# Generated by Django 5.1.3 on 2025-01-26 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0002_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='TRXid',
            field=models.CharField(default='Dues', max_length=30),
        ),
    ]
