# Generated by Django 5.1.3 on 2025-01-26 08:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0005_alter_orders_car_alter_orders_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='orderedat',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
