# Generated by Django 5.1.5 on 2025-01-27 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customuser', '0006_orders_orderedat'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='totalamount',
            field=models.IntegerField(default=0),
        ),
    ]
