# Generated by Django 5.1.5 on 2025-01-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
